main:
  prefix: '§e§lIN§6§lSU §f§l6 §r§7|§6 '
  #DO NOT TOUCH BEGIN-----------------------------------------------------------
  started: false
  #DO NOT TOUCH END-----------------------------------------------------------

dc:
  bot:
    token: 'MTAzOTkwNzkxODcxNzM5MDg2OA.G2t9Uc.FWt8rO66hKXYzB02gtDrbbFKuAKZHd7SRPn0X0'
    prefix: '!'
    channelid: ''



mysql:
  host: 'root'
  port: '3306'
  username: 'root'
  password: 'root'
  db: 'root'

  #DO NOT TOUCH THIS!