main:
  main: 'creperozelot'
  map: "world"
  kicktime: '20-30-02'
  playtime: '20-00-05'
  prefix: '§e§lIN§6§lSU §r§7|§6 '
  countdown:
    minutes: 15
  maintenance: true
  lobbyspawncoords:
    x: 9534
    y: 98
    z: 9447
  mapspawn: # start.x < end.x | start.z < end.z
    start:
      x: -342
      z: -327
    end:
      x: 114
      z: -554
  story:
    left_engine:
      x: 0
      y: 0
      z: 0
    right_engine:
      x: 0
      y: 0
      z: 0
  #DO NOT TOUCH BEGIN-----------------------------------------------------------
  started: false
  #DO NOT TOUCH END-------------------------------------------------------------
  autorunevents: false #BETA | DEFAULT: DISABLED

messages:
  endtime:
    title: '§c§lVorbei:'
    message: '§r§cDie Zeit zum Spielen ist für heute Vorbei!'
  errconsolerun: '§cDu kannst diese Command nur als Spieler ausführen!'
  death:
    entity_attack: '{player} ist an {entity} auf bodenloser Art und Weise gekillt worden!'
    fall: '{player} hat den Green gemacht, NEIIIIIIIN!'
    lava: '{player} ist in fließender Lava gestorben, Noob!'
    void: '{player} ist im Bodenlose verreckt.'
    magic: '{player} ist an Vikthors Magie gestorben'
    poison: '{player} ist an Gift verreckt!'
    thorns: '{player} ist an einer guten Rüstung gestorben!'
    wither: '{player} ist an einem Wither gestorben.'
    melting: '{player} ist geschmolzen, Kelb'
    contact: '{player} Ist an einem Kaktus oder so gestorben.'
    suicide: '{player} konnte das alles nicht mehr ertragen.'
    cramming: '{player} ist an Ahnungslosigkeit gestorben.'
    drowning: '{player} ist ertrunken, Lost?!'
    lightning: '{player} wurde von Vikthor seiner Macht getroffen!'
    projectile: '{player} wurde von {entity} (Main Character) zerschossen!'
    starvation: '{player} ist zu doof für´s essen!'
    suffocation: '{player} ist in einem bestehenden Block erstickt!'
    entity_explosion: '{player} wurde von {entity} zu Tode gebombt!'
    entity_sweep_attack: '{player} wurde von {entity} weg geschnetzelt'
    fire: '{player} wurde von Flame gegrillt'
    fire_tick: '{player} verbrennt gerade durch Flame'
    custom: '{player} ist an was unbekanntem gestorben!'
    hot_floor: '{player} wurde von Flame gekillt!'
    deagon_breath: '{player} ist an Vikthor seinem Atemzug gestorben!'
    falling_block: '{player} wurde vermutlich druch Kies oder Sand zerquetscht'
    fly_into_wall: '{player} musste ja versuchen in die Wand zu glitchen!'
    block_explosion: '{player} wurde von einem Explodierenden Item (TNT?) zerbombt!'
    others: '{player} ist jetzt in einer anderen Welt :('
#schema: question;answer
questions:
  - Was schrie Flame in INSU 4 während er in die Höhle an Tag 2 fiel?;NEIN
  - Wann war das erste INSU (bitte nur das Jahr)?;2020
  - Wer war der Gamemaster in INSU 1 (Kompletter Username Stand:2020)?;Toadenation
  - Wer hat mit ItsRazorPvP INSU 2 gewonnen (Kompletter Username Stand:2021)?;RealSertrix
  - Wer ist der Developer von INSU Staffel 6 (Kompletter Username)?;creperozelot
  - Wofür steht die Abkürzung INSU?;Insel Survival
story:
  airplane:
    start:
      x: 0
      y: 0
      z: 0
    inair:
      x: 0
      y: 0
      z: 0

dc:
  bot:
    token: 'MTAzOTkwNzkxODcxNzM5MDg2OA.G2t9Uc.FWt8rO66hKXYzB02gtDrbbFKuAKZHd7SRPn0X0'
    prefix: '!'
    channelid: ''



mysql:
  host: 'root'
  port: '3306'
  username: 'root'
  password: 'root'
  db: 'root'

  #DO NOT TOUCH THIS!
intime: false