name: INSU6
version: '${project.version}'
main: INSU.creperozelot.main
authors: [ creperozelot, PixelMandel ]
description: Insu 6 Plugin
website: https://the-flames.de
#  depend:
# - CrossplatForms
commands:
  spec:
    description: Setzt dich in den Spec Modus und Umgekehrt.
    permission: insu.admin.spec
    permission-message: §cDu hast keine Berechtigung dafür!
  glueckstreffer:
    description: Startet das Event Glückstreffer.
    permission: insu.admin.event.glueckstreffer
    permission-message: §cDu hast keine Berechtigung dafür!
  BetterWatchOut:
    description: Start das Event BetterWatchOut.
    permission: insu.admin.event.BetterWatchOut
    permission-message: §cDu hast keine Berechtigung dafür!