name: INSU6
version: '${project.version}'
main: INSU.creperozelot.main
authors: [ creperozelot, PixelMandel ]
description: Insu 6 Plugin
website: https://the-flames.de
#  depend:
# - CrossplatForms
commands:
  spec:
    description: Setzt dich in den Spec Modus und Umgekehrt.
    permission: insu.admin.spec
    permission-message: §cDu hast keine Berechtigung dafür!
  glueckstreffer:
    description: Startet das Event Glückstreffer.
    permission: insu.admin.event.glueckstreffer
    permission-message: §cDu hast keine Berechtigung dafür!
  BetterWatchOut:
    description: Start das Event BetterWatchOut.
    permission: insu.admin.event.BetterWatchOut
    permission-message: §cDu hast keine Berechtigung dafür!
  setairplanestart:
    description: Setze die Startkoordinaten von der Story (Flugzeug Boden)
    permission: insu.admin.story.airplane.start
    permission-message: §cDu hast keine Berechtigung dafür!
  reloadconfig:
    description: Lädt die Config neu
    permission: insu.admin.reloadconfig
    permission-message: §cDu hast keine Berechtigung dafür!
  startevent:
    description: Startet ein Event
    permission: insu.admin.eventstart
    permission-message: §cDu hast keine Berechtigung dafür!
  dev_seteventvar:
    description: Setzt die Event variable
    permission: insu.dev.var
    permission-message: §cDu hast keine Berechtigung dafür!
