name: INSU6
api: [1.13.2]
version: '${project.version}'
main: INSU.creperozelot.main
authors: [ creperozelot, PixelMandel ]
description: Insu 6 Plugin
website: https://the-flames.de
# - CrossplatForms
commands:
  spec:
    description: Setzt dich in den Spec Modus und Umgekehrt.
    permission: insu.admin.spec
    permission-message: §cDu hast keine Berechtigung dafür!
  setairplanestart:
    description: Setze die Startkoordinaten von der Story (Flugzeug Boden)
    permission: insu.admin.story.airplane.start
    permission-message: §cDu hast keine Berechtigung dafür!
  reloadconfig:
    description: Lädt die Config neu
    permission: insu.admin.reloadconfig
    permission-message: §cDu hast keine Berechtigung dafür!
  startevent:
    description: Startet ein Event
    permission: insu.admin.eventstart
    permission-message: §cDu hast keine Berechtigung dafür!
  dev_seteventvar:
    description: Setzt die Event variable
    permission: insu.dev.var
    permission-message: §cDu hast keine Berechtigung dafür!
  setairplaneair:
    description: Setze die Startkoordinaten von der Story (Flugzeug Air)
    permission: insu.admin.story.airplane.air
    permission-message: §cDu hast keine Berechtigung dafür!
  start:
    description: Startet das Projekt
    permission: insu.admin.start
    permission-message: §cDu hast keine Berechtigung dafür!
  mute:
    description: Muted einen Spieler
    permission: insu.admin.mute
    permission-message: §cDu hast keine Berechtigung dafür!
  unmute:
    description: Muted einen Spieler
    permission: insu.admin.unmute
    permission-message: §cDu hast keine Berechtigung dafür!
  dbreconnect:
    description: Startet die Datenbank Verbindung neu!
    permission: insu.admin.dbreconnect
    permission-message: §cDu hast keine Berechtigung dafür!
  teamchest:
    description: Öffnet die Teamchest!
    aliases:
      - tc
  tpup:
    description: Tpt alle Spieler nach oben!
    permission: insu.admin.tpup
    permission-message: §cDu hast keine Berechtigung dafür!
  dev_soundtest:
    description: Sound Test
    permission: insu.dev.soundtest
    permission-message: §cDu hast keine Berechtigung dafür!
  strike:
    description: Strike befehl um Spieler zu bestraffen!
    permission: insu.admin.strike
    permission-message: §cDu hast keine Berechtigung dafür!
  forcestart:
    description: Startet das Projekt SOFORT!
    permission: insu.admin.forcestart
    permission-message: §cDu hast keine Berechtigung dafür!
  dev_cforcestart:
    description: Startet das Projekt unabhängig davon ob der start true oder false ist.
    permission: insu.dev.cforcestart
    permission-message: §cDu hast keine Berechtigung dafür!
  ui:
    description: Öffnet das Admin Interface.
    permission: insu.admin.ui
    permission-message: §cDu hast keine Berechtigung dafür!
  switch-mode:
    description: Setzt den wartungsmodus.
    permission: insu.admin.maintenance
    permission-message: §cDu hast keine Berechtigung dafür!
    aliases:
      - maintence
      - maintenance
      - wartung
      - wartungen
  pvp:
    description: Setzt den PVP MODUS.
    permission: insu.admin.setpvp
    permission-message: §cDu hast keine Berechtigung dafür!